APP_NAME = json
VERSION = 0.0.2
INSTALL_PATH = /opt
# CFLAGS +=
PACKAGE_CONTENTS := ${SRC_PATH}/${APP_NAME}.h lib${APP_NAME}.a

PTREE_PROJECT_ID = 61120549
UNITEST_PROJECT_ID = 11728468

DEPENDENCIES += gitlab/${PTREE_PROJECT_ID}/0.0.6
DEPENDENCIES += gitlab/${UNITEST_PROJECT_ID}/0.2.0

STATIC_DEP = ptree
SHARED_DEP =

LDFLAGS += ${STATIC_DEP:%=-l%} ${SHARED_DEP:%=-l%}

