APP_NAME = json
VERSION = 0.0.2
INSTALL_PATH = /opt
# CFLAGS +=

HASH_TABLE_PROJECT_ID = 46645124
UNITEST_PROJECT_ID = 11728468

DEPENDENCIES += gitlab/${HASH_TABLE_PROJECT_ID}/0.1.3
DEPENDENCIES += gitlab/${UNITEST_PROJECT_ID}/0.2.0

STATIC_DEP = hash_table
SHARED_DEP =

LDFLAGS += ${STATIC_DEP:%=-l%} ${SHARED_DEP:%=-l%}

